# Generated by Django 5.0.1 on 2025-10-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lecture_sessions", "__first__"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CLICK", "클릭"),
                            ("LONG_CLICK", "길게 누르기"),
                            ("SCROLL", "스크롤"),
                            ("TEXT_INPUT", "텍스트 입력"),
                            ("SCREEN_CHANGE", "화면 전환"),
                            ("FOCUS", "포커스"),
                            ("SELECTION", "선택"),
                        ],
                        max_length=50,
                        verbose_name="이벤트 타입",
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(blank=True, null=True, verbose_name="이벤트 데이터"),
                ),
                (
                    "screen_info",
                    models.JSONField(blank=True, null=True, verbose_name="화면 정보"),
                ),
                (
                    "node_info",
                    models.JSONField(blank=True, null=True, verbose_name="노드 정보"),
                ),
                (
                    "parent_node_info",
                    models.JSONField(blank=True, null=True, verbose_name="부모 노드 정보"),
                ),
                (
                    "view_id_resource_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="뷰 ID 리소스 이름"
                    ),
                ),
                (
                    "content_description",
                    models.TextField(blank=True, verbose_name="콘텐츠 설명"),
                ),
                (
                    "is_sensitive_data",
                    models.BooleanField(default=False, verbose_name="민감 정보 여부"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="타임스탬프"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="lecture_sessions.lecturesession",
                        verbose_name="세션",
                    ),
                ),
                (
                    "subtask",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="tasks.subtask",
                        verbose_name="세부 단계",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "활동 로그",
                "verbose_name_plural": "활동 로그",
                "db_table": "activity_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="activity_lo_user_id_072db3_idx"
                    ),
                    models.Index(
                        fields=["subtask"], name="activity_lo_subtask_1c0c56_idx"
                    ),
                    models.Index(
                        fields=["session"], name="activity_lo_session_45d5f6_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="activity_lo_timesta_ef2c57_idx"
                    ),
                    models.Index(
                        fields=["view_id_resource_name"],
                        name="activity_lo_view_id_c981d6_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="activity_lo_event_t_dca05e_idx"
                    ),
                    models.Index(
                        fields=["is_sensitive_data"],
                        name="activity_lo_is_sens_9e5a20_idx",
                    ),
                ],
            },
        ),
    ]
