# Generated by Django 5.0.1 on 2025-11-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0002_recordingsession"),
        ("logs", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="bounds",
            field=models.CharField(
                blank=True,
                help_text="[좌상단x,y][우하단x,y] 형식",
                max_length=100,
                verbose_name="화면 좌표",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="is_clickable",
            field=models.BooleanField(default=False, verbose_name="클릭 가능 여부"),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="is_editable",
            field=models.BooleanField(default=False, verbose_name="편집 가능 여부"),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="활성화 여부"),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="is_focused",
            field=models.BooleanField(default=False, verbose_name="포커스 여부"),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="recording_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_events",
                to="lecture_sessions.recordingsession",
                verbose_name="녹화 세션",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="server_received_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="서버가 이벤트를 수신한 시각",
                null=True,
                verbose_name="서버 수신 시각",
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["recording_session"], name="activity_lo_recordi_dcb667_idx"
            ),
        ),
    ]
