# Generated by Django 5.0.1 on 2025-11-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0002_activitylog_bounds_activitylog_is_clickable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="device_id",
            field=models.CharField(
                blank=True,
                help_text="익명 사용자 식별용 기기 고유값",
                max_length=255,
                verbose_name="기기 ID",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
    ]
