# Generated by Django 5.0.1 on 2025-11-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0003_activitylog_device_id_alter_activitylog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CLICK", "클릭"),
                    ("LONG_CLICK", "길게 누르기"),
                    ("SCROLL", "스크롤"),
                    ("TEXT_INPUT", "텍스트 입력"),
                    ("SCREEN_CHANGE", "화면 전환"),
                    ("FOCUS", "포커스"),
                    ("SELECTION", "선택"),
                    ("WINDOW_CHANGE", "윈도우 변경"),
                    ("VIEW_CLICKED", "뷰 클릭"),
                    ("VIEW_FOCUSED", "뷰 포커스"),
                    ("VIEW_TEXT_CHANGED", "텍스트 변경"),
                    ("VIEW_SCROLLED", "뷰 스크롤"),
                    ("WINDOW_STATE_CHANGED", "윈도우 상태 변경"),
                    ("WINDOW_CONTENT_CHANGED", "윈도우 콘텐츠 변경"),
                ],
                max_length=50,
                verbose_name="이벤트 타입",
            ),
        ),
    ]
