# Generated by Django 5.0.1 on 2025-10-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lecture_sessions", "__first__"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("MANUAL", "수동 요청"), ("AUTO", "자동 감지")],
                        max_length=20,
                        verbose_name="요청 타입",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(blank=True, null=True, verbose_name="컨텍스트 데이터"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("ANALYZING", "분석 중"),
                            ("RESOLVED", "해결됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="요청 시각"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="해결 시각"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_requests",
                        to="lecture_sessions.lecturesession",
                        verbose_name="세션",
                    ),
                ),
                (
                    "subtask",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="help_requests",
                        to="tasks.subtask",
                        verbose_name="세부 단계",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "도움 요청",
                "verbose_name_plural": "도움 요청",
                "db_table": "help_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MGptAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_input", models.JSONField(verbose_name="분석 입력")),
                ("analysis_output", models.JSONField(verbose_name="분석 출력")),
                (
                    "problem_diagnosis",
                    models.TextField(blank=True, verbose_name="문제 진단"),
                ),
                ("suggested_help", models.TextField(blank=True, verbose_name="추천 도움말")),
                (
                    "confidence_score",
                    models.FloatField(blank=True, null=True, verbose_name="신뢰도"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="분석 시각"),
                ),
                (
                    "help_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mgpt_analysis",
                        to="help.helprequest",
                        verbose_name="도움 요청",
                    ),
                ),
            ],
            options={
                "verbose_name": "M-GPT 분석",
                "verbose_name_plural": "M-GPT 분석",
                "db_table": "mgpt_analyses",
            },
        ),
        migrations.CreateModel(
            name="HelpResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "help_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "텍스트"),
                            ("VOICE", "음성"),
                            ("OVERLAY", "오버레이"),
                            ("VIDEO", "비디오"),
                        ],
                        max_length=20,
                        verbose_name="도움 타입",
                    ),
                ),
                ("help_content", models.TextField(verbose_name="도움 내용")),
                (
                    "displayed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="표시 시각"),
                ),
                (
                    "feedback_rating",
                    models.IntegerField(blank=True, null=True, verbose_name="평점"),
                ),
                ("feedback_text", models.TextField(blank=True, verbose_name="피드백 텍스트")),
                (
                    "feedback_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="피드백 시각"),
                ),
                (
                    "help_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="help.helprequest",
                        verbose_name="도움 요청",
                    ),
                ),
                (
                    "mgpt_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="help.mgptanalysis",
                        verbose_name="M-GPT 분석",
                    ),
                ),
            ],
            options={
                "verbose_name": "도움 응답",
                "verbose_name_plural": "도움 응답",
                "db_table": "help_responses",
            },
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(fields=["user"], name="help_reques_user_id_49bf72_idx"),
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(
                fields=["session"], name="help_reques_session_8cad01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(fields=["status"], name="help_reques_status_e14f95_idx"),
        ),
        migrations.AddIndex(
            model_name="helprequest",
            index=models.Index(
                fields=["created_at"], name="help_reques_created_a1fd4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mgptanalysis",
            index=models.Index(
                fields=["help_request"], name="mgpt_analys_help_re_1da232_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="helpresponse",
            index=models.Index(
                fields=["help_request"], name="help_respon_help_re_c48ada_idx"
            ),
        ),
    ]
