# Generated by Django 5.0.1 on 2025-10-28 16:14

import apps.sessions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lectures", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="세션 제목")),
                (
                    "session_code",
                    models.CharField(
                        default=apps.sessions.models.generate_session_code,
                        max_length=20,
                        unique=True,
                        verbose_name="입장 코드",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "대기실"),
                            ("IN_PROGRESS", "진행 중"),
                            ("ENDED", "종료"),
                            ("REVIEW_MODE", "복습 모드"),
                        ],
                        default="WAITING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "qr_code_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="QR 코드 URL"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="예정 시각"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작 시각"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="종료 시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "current_subtask",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_in_sessions",
                        to="tasks.subtask",
                        verbose_name="현재 진행 단계",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="강사",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="lectures.lecture",
                        verbose_name="강의",
                    ),
                ),
            ],
            options={
                "verbose_name": "강의 세션",
                "verbose_name_plural": "강의 세션",
                "db_table": "lecture_sessions",
            },
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "대기 중"),
                            ("ACTIVE", "활성"),
                            ("COMPLETED", "완료"),
                            ("DISCONNECTED", "연결 끊김"),
                        ],
                        default="WAITING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="입장 시각"),
                ),
                (
                    "last_active_at",
                    models.DateTimeField(auto_now=True, verbose_name="마지막 활동"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료 시각"),
                ),
                (
                    "current_subtask",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participant_progress",
                        to="tasks.subtask",
                        verbose_name="현재 단계",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="lecture_sessions.lecturesession",
                        verbose_name="세션",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "세션 참가자",
                "verbose_name_plural": "세션 참가자",
                "db_table": "session_participants",
            },
        ),
        migrations.CreateModel(
            name="SessionStepControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("START_STEP", "단계 시작"),
                            ("END_STEP", "단계 종료"),
                            ("PAUSE", "일시 정지"),
                            ("RESUME", "재개"),
                            ("SKIP", "건너뛰기"),
                        ],
                        max_length=20,
                        verbose_name="액션",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="메시지")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="기록 시각"),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_controls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="강사",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_controls",
                        to="lecture_sessions.lecturesession",
                        verbose_name="세션",
                    ),
                ),
                (
                    "subtask",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_controls",
                        to="tasks.subtask",
                        verbose_name="단계",
                    ),
                ),
            ],
            options={
                "verbose_name": "단계 제어 기록",
                "verbose_name_plural": "단계 제어 기록",
                "db_table": "session_step_control",
            },
        ),
        migrations.AddIndex(
            model_name="lecturesession",
            index=models.Index(
                fields=["lecture"], name="lecture_ses_lecture_e65ea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lecturesession",
            index=models.Index(
                fields=["instructor"], name="lecture_ses_instruc_ef5729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lecturesession",
            index=models.Index(
                fields=["session_code"], name="lecture_ses_session_da5f0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lecturesession",
            index=models.Index(fields=["status"], name="lecture_ses_status_8def09_idx"),
        ),
        migrations.AddIndex(
            model_name="lecturesession",
            index=models.Index(
                fields=["scheduled_at"], name="lecture_ses_schedul_e25dc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(
                fields=["session"], name="session_par_session_3676a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(fields=["user"], name="session_par_user_id_d6ddcb_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(fields=["status"], name="session_par_status_32b2ff_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(
                fields=["last_active_at"], name="session_par_last_ac_b96ad3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sessionparticipant",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="sessionstepcontrol",
            index=models.Index(
                fields=["session"], name="session_ste_session_55711c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionstepcontrol",
            index=models.Index(
                fields=["subtask"], name="session_ste_subtask_8c06cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionstepcontrol",
            index=models.Index(
                fields=["created_at"], name="session_ste_created_a0c9d9_idx"
            ),
        ),
    ]
