# Generated by Django 5.0.1 on 2025-11-16 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0001_initial"),
        ("lectures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="녹화 제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECORDING", "녹화 중"),
                            ("COMPLETED", "완료"),
                            ("PROCESSING", "처리 중"),
                            ("FAILED", "실패"),
                        ],
                        default="RECORDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("event_count", models.IntegerField(default=0, verbose_name="이벤트 수")),
                (
                    "duration_seconds",
                    models.IntegerField(
                        default=0, help_text="녹화 시작부터 종료까지의 시간", verbose_name="녹화 시간(초)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작 시각"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="종료 시각"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="강의자",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordings",
                        to="lectures.lecture",
                        verbose_name="생성된 강의",
                    ),
                ),
            ],
            options={
                "verbose_name": "녹화 세션",
                "verbose_name_plural": "녹화 세션",
                "db_table": "recording_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instructor"], name="recording_s_instruc_c25789_idx"
                    ),
                    models.Index(
                        fields=["status"], name="recording_s_status_b4c958_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="recording_s_created_203cf2_idx"
                    ),
                    models.Index(
                        fields=["lecture"], name="recording_s_lecture_18cadf_idx"
                    ),
                ],
            },
        ),
    ]
