# Generated by Django 5.0.1 on 2025-11-25 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0002_recordingsession"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sessionparticipant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="device_id",
            field=models.CharField(
                blank=True,
                help_text="익명 참가자의 기기 고유 식별자",
                max_length=255,
                null=True,
                verbose_name="기기 ID",
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="화면에 표시될 참가자 이름",
                max_length=100,
                verbose_name="표시 이름",
            ),
        ),
        migrations.AlterField(
            model_name="sessionparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionparticipant",
            index=models.Index(
                fields=["device_id"], name="session_par_device__a19f07_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("device_id__isnull", False)),
                fields=("session", "device_id"),
                name="unique_session_device",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="unique_session_user",
            ),
        ),
    ]
