# Generated by Django 5.0.1 on 2025-11-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0003_alter_sessionparticipant_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="익명 참가자 식별용",
                        max_length=255,
                        verbose_name="기기 ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="screenshots/%Y/%m/%d/", verbose_name="스크린샷 이미지"
                    ),
                ),
                ("captured_at", models.DateTimeField(verbose_name="캡처 시각")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시각"),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="lecture_sessions.sessionparticipant",
                        verbose_name="참가자",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="lecture_sessions.lecturesession",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "학생 스크린샷",
                "verbose_name_plural": "학생 스크린샷",
                "db_table": "student_screenshots",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "participant"],
                        name="student_scr_session_68eefe_idx",
                    ),
                    models.Index(
                        fields=["session", "device_id"],
                        name="student_scr_session_6377d0_idx",
                    ),
                    models.Index(
                        fields=["captured_at"], name="student_scr_capture_be22c7_idx"
                    ),
                ],
            },
        ),
    ]
