# Generated by Django 5.0.1 on 2025-11-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0004_studentscreenshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionparticipant",
            name="completed_subtasks",
            field=models.JSONField(
                default=list,
                help_text="완료한 단계 ID 목록 (JSON Array)",
                verbose_name="완료된 단계 목록",
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="last_completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="마지막 완료 시각"),
        ),
    ]
