# Generated by Django 5.0.1 on 2025-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0005_sessionparticipant_completed_subtasks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingsession",
            name="analysis_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="분석 실패 시 오류 메시지 저장",
                verbose_name="분석 오류 메시지",
            ),
        ),
        migrations.AddField(
            model_name="recordingsession",
            name="analysis_result",
            field=models.JSONField(
                blank=True,
                help_text="GPT 분석으로 생성된 단계 목록 (JSON Array)",
                null=True,
                verbose_name="분석 결과",
            ),
        ),
        migrations.AddField(
            model_name="recordingsession",
            name="analyzed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="분석 완료 시각"),
        ),
        migrations.AlterField(
            model_name="recordingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECORDING", "녹화 중"),
                    ("COMPLETED", "완료"),
                    ("PROCESSING", "처리 중"),
                    ("ANALYZED", "분석 완료"),
                    ("FAILED", "실패"),
                ],
                default="RECORDING",
                max_length=20,
                verbose_name="상태",
            ),
        ),
    ]
