# Generated by Django 5.0.1 on 2025-12-03 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0005_sessionparticipant_completed_subtasks_and_more"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingsession",
            name="analysis_error",
            field=models.TextField(
                blank=True, help_text="GPT 분석 실패 시 오류 메시지", verbose_name="분석 오류"
            ),
        ),
        migrations.AlterField(
            model_name="recordingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECORDING", "녹화 중"),
                    ("COMPLETED", "완료"),
                    ("PROCESSING", "GPT 분석 중"),
                    ("ANALYZED", "분석 완료"),
                    ("CONVERTED", "강의 변환됨"),
                    ("FAILED", "실패"),
                ],
                default="RECORDING",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.CreateModel(
            name="RecordingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField(verbose_name="단계 번호")),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "event_time",
                    models.BigIntegerField(
                        blank=True,
                        help_text="밀리초 단위 타임스탬프",
                        null=True,
                        verbose_name="이벤트 시각",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(blank=True, max_length=50, verbose_name="이벤트 타입"),
                ),
                (
                    "package_name",
                    models.CharField(blank=True, max_length=255, verbose_name="패키지명"),
                ),
                (
                    "class_name",
                    models.CharField(blank=True, max_length=255, verbose_name="클래스명"),
                ),
                ("text", models.TextField(blank=True, verbose_name="텍스트")),
                (
                    "content_description",
                    models.TextField(blank=True, verbose_name="콘텐츠 설명"),
                ),
                (
                    "view_id",
                    models.CharField(blank=True, max_length=255, verbose_name="뷰 ID"),
                ),
                (
                    "bounds",
                    models.CharField(blank=True, max_length=100, verbose_name="화면 좌표"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "recording_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="lecture_sessions.recordingsession",
                        verbose_name="녹화 세션",
                    ),
                ),
                (
                    "subtask",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_recording_steps",
                        to="tasks.subtask",
                        verbose_name="변환된 Subtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "녹화 단계",
                "verbose_name_plural": "녹화 단계",
                "db_table": "recording_steps",
                "ordering": ["step_number"],
                "indexes": [
                    models.Index(
                        fields=["recording_session"],
                        name="recording_s_recordi_bc5d0a_idx",
                    ),
                    models.Index(
                        fields=["step_number"], name="recording_s_step_nu_c562ab_idx"
                    ),
                ],
                "unique_together": {("recording_session", "step_number")},
            },
        ),
    ]
