# Generated by Django 5.0.1 on 2025-12-09 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0006_add_recording_analysis_fields"),
        ("lectures", "0001_initial"),
        ("tasks", "0002_add_flask_sync_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recordingsession",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recordings",
                to="tasks.task",
                verbose_name="변환된 과제",
            ),
        ),
        migrations.AlterField(
            model_name="recordingsession",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recording_sessions",
                to="lectures.lecture",
                verbose_name="연결된 강의",
            ),
        ),
        migrations.AddIndex(
            model_name="recordingsession",
            index=models.Index(fields=["task"], name="recording_s_task_id_4f9967_idx"),
        ),
    ]
