# Generated by Django 5.0.1 on 2025-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture_sessions", "0006_add_recording_step_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordingsession",
            name="analysis_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="GPT 분석 실패 시 오류 메시지",
                verbose_name="분석 오류",
            ),
        ),
    ]
