# Generated by Django 5.0.1 on 2025-10-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lecture_sessions", "__first__"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "시작 안함"),
                            ("IN_PROGRESS", "진행 중"),
                            ("COMPLETED", "완료"),
                            ("HELP_NEEDED", "도움 필요"),
                        ],
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작 시각"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료 시각"),
                ),
                ("attempts", models.IntegerField(default=0, verbose_name="시도 횟수")),
                ("help_count", models.IntegerField(default=0, verbose_name="도움 요청 횟수")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progress",
                        to="lecture_sessions.lecturesession",
                        verbose_name="세션",
                    ),
                ),
                (
                    "subtask",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="tasks.subtask",
                        verbose_name="세부 단계",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "진행 상태",
                "verbose_name_plural": "진행 상태",
                "db_table": "user_progress",
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_progre_user_id_77f83f_idx"
                    ),
                    models.Index(
                        fields=["subtask"], name="user_progre_subtask_f5625d_idx"
                    ),
                    models.Index(
                        fields=["session"], name="user_progre_session_89c746_idx"
                    ),
                    models.Index(
                        fields=["status"], name="user_progre_status_493ce2_idx"
                    ),
                ],
                "unique_together": {("user", "subtask", "session")},
            },
        ),
    ]
