# Generated by Django 5.0.1 on 2025-10-28 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, unique=True, verbose_name="이메일"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="전화번호",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="나이")),
                (
                    "role",
                    models.CharField(
                        choices=[("INSTRUCTOR", "강사"), ("STUDENT", "학생")],
                        max_length=20,
                        verbose_name="역할",
                    ),
                ),
                (
                    "digital_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BEGINNER", "초급"),
                            ("INTERMEDIATE", "중급"),
                            ("ADVANCED", "고급"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="디지털 수준",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 여부")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프 여부")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성일시"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="마지막 로그인"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
                "db_table": "users",
                "indexes": [
                    models.Index(fields=["role"], name="users_role_0ace22_idx"),
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                ],
            },
        ),
    ]
