# Generated by Django 5.0.1 on 2025-10-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("order_index", models.IntegerField(verbose_name="순서")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="lectures.lecture",
                        verbose_name="강의",
                    ),
                ),
            ],
            options={
                "verbose_name": "과제",
                "verbose_name_plural": "과제",
                "db_table": "tasks",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="Subtask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("order_index", models.IntegerField(verbose_name="순서")),
                (
                    "target_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLICK", "클릭"),
                            ("LONG_CLICK", "길게 누르기"),
                            ("SCROLL", "스크롤"),
                            ("INPUT", "입력"),
                            ("NAVIGATE", "화면 이동"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="목표 액션",
                    ),
                ),
                (
                    "target_element_hint",
                    models.TextField(blank=True, verbose_name="UI 요소 힌트"),
                ),
                ("guide_text", models.TextField(blank=True, verbose_name="안내 문구")),
                (
                    "voice_guide_text",
                    models.TextField(blank=True, verbose_name="음성 안내 문구"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                        verbose_name="과제",
                    ),
                ),
            ],
            options={
                "verbose_name": "세부 단계",
                "verbose_name_plural": "세부 단계",
                "db_table": "subtasks",
                "ordering": ["order_index"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["lecture"], name="tasks_lecture_f460b7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("lecture", "order_index")},
        ),
        migrations.AddIndex(
            model_name="subtask",
            index=models.Index(fields=["task"], name="subtasks_task_id_acf350_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subtask",
            unique_together={("task", "order_index")},
        ),
    ]
