# Generated by Django 5.0.1 on 2025-12-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="bounds",
            field=models.CharField(
                blank=True,
                default="",
                help_text="UI 요소 위치 [x1,y1][x2,y2]",
                max_length=100,
                verbose_name="화면 좌표",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="content_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="contentDescription 값",
                max_length=500,
                verbose_name="접근성 설명",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="target_class",
            field=models.CharField(
                blank=True,
                default="",
                help_text="UI 요소 클래스명",
                max_length=255,
                verbose_name="클래스명",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="target_package",
            field=models.CharField(
                blank=True,
                default="",
                help_text="앱 패키지 이름",
                max_length=255,
                verbose_name="패키지명",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="text",
            field=models.TextField(
                blank=True, default="", help_text="UI 요소의 표시 텍스트", verbose_name="UI 텍스트"
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="time",
            field=models.BigIntegerField(
                blank=True,
                help_text="이벤트 발생 시간 (Unix 밀리초)",
                null=True,
                verbose_name="이벤트 시간",
            ),
        ),
        migrations.AddField(
            model_name="subtask",
            name="view_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="viewId 리소스 이름",
                max_length=255,
                verbose_name="뷰 ID",
            ),
        ),
    ]
