# Generated by Django 5.0.1 on 2025-12-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0001_initial"),
        ("tasks", "0002_add_flask_sync_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="task",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="lectures.lecture",
                verbose_name="강의",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="order_index",
            field=models.IntegerField(default=0, verbose_name="순서"),
        ),
    ]
