# Generated by Django 5.0.1 on 2025-12-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0001_initial"),
        ("tasks", "0003_allow_task_without_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="source_task",
            field=models.ForeignKey(
                blank=True,
                help_text="이 과제가 복사된 원본 과제 (템플릿)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="tasks.task",
                verbose_name="원본 과제",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["source_task"], name="tasks_source__d78eca_idx"),
        ),
    ]
