# Generated by Django 5.0.1 on 2025-10-28 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, verbose_name="썸네일 URL"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="강사",
                    ),
                ),
            ],
            options={
                "verbose_name": "강의",
                "verbose_name_plural": "강의",
                "db_table": "lectures",
            },
        ),
        migrations.CreateModel(
            name="UserLectureEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일시"),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="lectures.lecture",
                        verbose_name="강의",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "수강 등록",
                "verbose_name_plural": "수강 등록",
                "db_table": "user_lecture_enrollments",
            },
        ),
        migrations.AddIndex(
            model_name="lecture",
            index=models.Index(
                fields=["instructor"], name="lectures_instruc_07dc82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lecture",
            index=models.Index(
                fields=["is_active"], name="lectures_is_acti_393d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlectureenrollment",
            index=models.Index(fields=["user"], name="user_lectur_user_id_2d2971_idx"),
        ),
        migrations.AddIndex(
            model_name="userlectureenrollment",
            index=models.Index(
                fields=["lecture"], name="user_lectur_lecture_8da742_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userlectureenrollment",
            unique_together={("user", "lecture")},
        ),
    ]
